name: CI3
on: 
  workflow_dispatch:
 
jobs:
  setup-job:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        name: Setup on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: cruizba/ubuntu-dind
            options: --privileged
            run: |
                echo OK && sleep 15
            shell: bash

  on-job1:
    runs-on: ubuntu-latest
    needs: setup-job
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        name: Setup on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: cruizba/ubuntu-dind
            options: --privileged
            run: |
                echo OK && sleep 15
            shell: bash

  on-job2:
    runs-on: ubuntu-latest
    needs: on-job1
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        name: Setup on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: cruizba/ubuntu-dind
            options: --privileged
            run: |
                echo OK && sleep 15
            shell: bash

  on-job3:
    runs-on: ubuntu-latest
    needs: on-job2
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
         Port: [10011, 10012]
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        name: Setup on Port ${{matrix.Port}}
      - name: Run the Server build process
        uses: addnab/docker-run-action@v3
        with:
            image: cruizba/ubuntu-dind
            options: --privileged
            run: |
                echo OK && sleep 15
            shell: bash
